{"name": "Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 409 == 404\n +  where 409 = <Response [409]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x000002B12DE070B0>\ncourier_login_valid_creds = ({'firstName': '37ze50l67q', 'login': 'dtv5h8628h', 'password': '7wov5cnh88'}, 289732)\ncreated_order_data = (946693, {'order': {'address': 'Konoha, 142 apt.', 'cancelled': False, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', ...}})\n\n    @allure.title('Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_not_existing_order_id_fail(\n            self,\n            courier_login_valid_creds,\n            created_order_data,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        order_id = order_helpers.get_order_id(created_order_data[1])\n        order_helpers.cancel_order(created_order_data[0])\n        resp = order_helpers.accept_order(\n            order_id,\n            courier_id,\n        )\n>       assert resp.status_code == 404\nE       assert 409 == 404\nE        +  where 409 = <Response [409]>.status_code\n\ntests\\orders\\test_accept_order.py:70: AssertionError"}, "steps": [{"name": "Получить id заказа", "status": "passed", "parameters": [{"name": "order_data", "value": "{'order': {'id': 268024, 'firstName': 'Naruto', 'lastName': 'Uchiha', 'address': 'Konoha, 142 apt.', 'metroStation': '4', 'phone': '+7 800 355 35 35', 'rentTime': 5, 'deliveryDate': '2020-06-06T00:00:00.000Z', 'track': 946693, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', 'cancelled': False, 'finished': False, 'inDelivery': False, 'createdAt': '2024-04-10T17:12:18.482Z', 'updatedAt': '2024-04-10T17:12:18.482Z', 'status': 0}}"}], "start": 1712769139313, "stop": 1712769139313}, {"name": "Отменить заказ по треку 946693", "status": "passed", "parameters": [{"name": "track", "value": "946693"}], "start": 1712769139313, "stop": 1712769139656}, {"name": "Принять заказ с id 268024 курьером с courier_id 289732", "status": "passed", "parameters": [{"name": "order_id", "value": "268024"}, {"name": "courier_id", "value": "289732"}], "start": 1712769139657, "stop": 1712769139992}], "start": 1712769139312, "stop": 1712769139992, "uuid": "aa8f993b-1030-4b34-8af9-1816e3962c2d", "historyId": "4444eae044c9ecdb8fb45e0d56cead4e", "testCaseId": "4444eae044c9ecdb8fb45e0d56cead4e", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_not_existing_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "4340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}