{"name": "Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 409 == 404\n +  where 409 = <Response [409]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x00000145C4E8F830>\ncourier_login_valid_creds = ({'firstName': 'kjlpmtx2uk', 'login': 't6r2obavm9', 'password': 'cndfinrmtz'}, 292926)\ncreated_order_data = (428914, {'order': {'address': 'Konoha, 142 apt.', 'cancelled': False, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', ...}})\n\n    @allure.title('Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_not_existing_order_id_fail(\n            self,\n            courier_login_valid_creds,\n            created_order_data,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        order_id = order_helpers.get_order_id(created_order_data[1])\n        order_helpers.cancel_order(created_order_data[0])\n        resp = order_helpers.accept_order(\n            order_id,\n            courier_id,\n        )\n>       assert resp.status_code == 404\nE       assert 409 == 404\nE        +  where 409 = <Response [409]>.status_code\n\ntests\\orders\\test_accept_order.py:71: AssertionError"}, "steps": [{"name": "Получить id заказа", "status": "passed", "parameters": [{"name": "order_data", "value": "{'order': {'id': 269840, 'firstName': 'Naruto', 'lastName': 'Uchiha', 'address': 'Konoha, 142 apt.', 'metroStation': '4', 'phone': '+7 800 355 35 35', 'rentTime': 5, 'deliveryDate': '2020-06-06T00:00:00.000Z', 'track': 428914, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', 'cancelled': False, 'finished': False, 'inDelivery': False, 'createdAt': '2024-04-15T05:50:45.519Z', 'updatedAt': '2024-04-15T05:50:45.519Z', 'status': 0}}"}], "start": 1713160246595, "stop": 1713160246595}, {"name": "Отменить заказ по треку 428914", "status": "passed", "parameters": [{"name": "track", "value": "428914"}], "start": 1713160246595, "stop": 1713160246942}, {"name": "Принять заказ с id 269840 курьером с courier_id 292926", "status": "passed", "parameters": [{"name": "order_id", "value": "269840"}, {"name": "courier_id", "value": "292926"}], "start": 1713160246943, "stop": 1713160247280}], "start": 1713160246594, "stop": 1713160247280, "uuid": "74f506ad-3aa2-4443-9293-804821d9b8c3", "historyId": "4444eae044c9ecdb8fb45e0d56cead4e", "testCaseId": "4444eae044c9ecdb8fb45e0d56cead4e", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_not_existing_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "25024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}