{"name": "Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно", "status": "failed", "statusDetails": {"message": "AssertionError: assert 409 == 404\n +  where 409 = <Response [409]>.status_code", "trace": "self = <tests.orders.test_accept_order.TestAcceptOrder object at 0x000001F42BCAB7A0>\ncourier_login_valid_creds = ({'firstName': 'sr7iktk05q', 'login': 'wewlhi3i15', 'password': '2tqbark0o8'}, 289782)\ncreated_order_data = (966495, {'order': {'address': 'Konoha, 142 apt.', 'cancelled': False, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', ...}})\n\n    @allure.title('Принять заказ. Если передан id не существующего заказа и передан id курьера, НЕ успешно')\n    def test_accept_order_with_not_existing_order_id_fail(\n            self,\n            courier_login_valid_creds,\n            created_order_data,\n    ):\n        courier_id = courier_login_valid_creds[1]\n        order_helpers = OrderHelpers()\n        order_id = order_helpers.get_order_id(created_order_data[1])\n        order_helpers.cancel_order(created_order_data[0])\n        resp = order_helpers.accept_order(\n            order_id,\n            courier_id,\n        )\n>       assert resp.status_code == 404\nE       assert 409 == 404\nE        +  where 409 = <Response [409]>.status_code\n\ntests\\orders\\test_accept_order.py:71: AssertionError"}, "steps": [{"name": "Получить id заказа", "status": "passed", "parameters": [{"name": "order_data", "value": "{'order': {'id': 268046, 'firstName': 'Naruto', 'lastName': 'Uchiha', 'address': 'Konoha, 142 apt.', 'metroStation': '4', 'phone': '+7 800 355 35 35', 'rentTime': 5, 'deliveryDate': '2020-06-06T00:00:00.000Z', 'track': 966495, 'color': ['BLACK'], 'comment': 'Saske, come back to Konoha', 'cancelled': False, 'finished': False, 'inDelivery': False, 'createdAt': '2024-04-10T17:51:05.376Z', 'updatedAt': '2024-04-10T17:51:05.376Z', 'status': 0}}"}], "start": 1712771466233, "stop": 1712771466233}, {"name": "Отменить заказ по треку 966495", "status": "passed", "parameters": [{"name": "track", "value": "966495"}], "start": 1712771466233, "stop": 1712771466574}, {"name": "Принять заказ с id 268046 курьером с courier_id 289782", "status": "passed", "parameters": [{"name": "order_id", "value": "268046"}, {"name": "courier_id", "value": "289782"}], "start": 1712771466575, "stop": 1712771467021}], "start": 1712771466232, "stop": 1712771467021, "uuid": "06324573-e17e-479b-8859-d212495bc66a", "historyId": "4444eae044c9ecdb8fb45e0d56cead4e", "testCaseId": "4444eae044c9ecdb8fb45e0d56cead4e", "fullName": "tests.orders.test_accept_order.TestAcceptOrder#test_accept_order_with_not_existing_order_id_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "28688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_accept_order"}]}